# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The DANK Bank
description: The Decentralized Bank is an open source blockchain project to create a community-run decentralized financial institution.
baseurl: / # the subpath of your site, e.g. /support
url: https://dank.finance # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: The Decentralized Bank #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: The DANK Bank
header: The Decentralized Bank
subheader: Supercharged Growth Capital for Crypto Businesses

meta_image: odin-meta.png

# Social Links
twitter_username: seibelj
facebook_page:
github_username: seibelj
email: seibeljames@gmail.com
linkedin_page: https://www.linkedin.com/in/seibeljames/
instagram_username: 


# Navivation
nav_item_one: Telegram
nav_item_one_link: https://t.me/TheDankBank

nav_button: Whitepaper
nav_button_link: https://docs.google.com/document/d/1eHQeZFpix2LqVOGVmXxliiFWEyiGAI8fxI8qTZPCu2I/edit?usp=sharing

# More Help
help_one_title: Telegram
help_one_content: Join The DANK Bank Community
help_one_button: Join the Telegram Group
help_one_link: https://t.me/TheDankBank

help_two_title: Whitepaper
help_two_content: Learn how The Decentralized Bank is disrupting crypto finance.
help_two_button: Read the Whitepaper
help_two_link: https://docs.google.com/document/d/1eHQeZFpix2LqVOGVmXxliiFWEyiGAI8fxI8qTZPCu2I/edit?usp=sharing

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
